### ISSUE TITLE
Exception - Call to a member function get_contextid() on boolean

### ISSUE THREAD

**Issue by fishfree** [UNEDLabs/moodle-mod_ejsapp#19]
I down[ this experiment zip file](https://unilabs.dia.uned.es/pluginfile.php/10549/mod_data/content/145/ServoMotor.zip) and upload it to an EJSApp activity, click on Save and  Display button, the page shows error: 
`Exception - Call to a member function get_contextid() on boolean`

Moodle 3.7.1
EjsApp: 4.0 (Build: 2019112102)

**Comment by Ravenink** [comment]
Thanks for reporting this.

When I uploaded the file in my Moodle (also 3.7 and also with EJSApp 4.0), I get a different error, but the simulation is not displayed neither. This is because that file was packaged with a quite old version of EjsS. If you open the .ejss file within the zip file with EjsS and repackage the simulation into a new zip file, it should work.

For now, I replaced two virtual lab files in the repository (all of them are too old and we need to rebuild them with a newer version of EjsS, so thanks for bringing my attention to this!): the motor, which is the one you tried (https://unilabs.dia.uned.es/pluginfile.php/10549/mod_data/content/145/ServoMotor.zip) and the inverted pendulum (https://unilabs.dia.uned.es/pluginfile.php/10549/mod_data/content/135/FurutaPendulum.zip)

Download any of these two and try again. It should work, but if you have any trouble, please let me know.

**Comment by fishfree** [comment]
@Ravenink Thank you very much! Your modified packages work like a charm!

**Comment by Ravenink** [comment]
Good to know 😁
One more thing, in case you are interested... I also updated the rest of the virtual lab applications in UNILabs repository, except the one of the ball and plate. So all them (except the mentioned one) should work.
